name: {{ cookiecutter.conda_environment_name }}
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupytext
  - ipykernel
  - matplotlib
  - cartopy
  - cmocean
  - numpy
  - pandas
  - scipy
  - tqdm
  - xarray
  - netcdf4
  - dask
  - seawater
  - gsw
  - pip
{%- if cookiecutter.as_python_package == 'y' %}
  - pip:
      - "-e ."
{%- endif %}
